<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AlbumTrack', 'doctrine');

/**
 * BaseAlbumTrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $album_id
 * @property integer $track_id
 * @property Album $Album
 * 
 * @method integer    getAlbumId()  Returns the current record's "album_id" value
 * @method integer    getTrackId()  Returns the current record's "track_id" value
 * @method Album      getAlbum()    Returns the current record's "Album" value
 * @method AlbumTrack setAlbumId()  Sets the current record's "album_id" value
 * @method AlbumTrack setTrackId()  Sets the current record's "track_id" value
 * @method AlbumTrack setAlbum()    Sets the current record's "Album" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbumTrack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album_track');
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('track_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}