<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AlbumMusicalGender', 'doctrine');

/**
 * BaseAlbumMusicalGender
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $album_id
 * @property integer $musical_gender_id
 * @property MusicalGender $MusicalGender
 * @property Album $Album
 * 
 * @method integer            getAlbumId()           Returns the current record's "album_id" value
 * @method integer            getMusicalGenderId()   Returns the current record's "musical_gender_id" value
 * @method MusicalGender      getMusicalGender()     Returns the current record's "MusicalGender" value
 * @method Album              getAlbum()             Returns the current record's "Album" value
 * @method AlbumMusicalGender setAlbumId()           Sets the current record's "album_id" value
 * @method AlbumMusicalGender setMusicalGenderId()   Sets the current record's "musical_gender_id" value
 * @method AlbumMusicalGender setMusicalGender()     Sets the current record's "MusicalGender" value
 * @method AlbumMusicalGender setAlbum()             Sets the current record's "Album" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbumMusicalGender extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album_musical_gender');
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('musical_gender_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MusicalGender', array(
             'local' => 'musical_gender_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Album', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}