<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArtistMusicalGender', 'doctrine');

/**
 * BaseArtistMusicalGender
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $artist_id
 * @property integer $musical_gender_id
 * @property Artist $Artist
 * @property MusicalGender $MusicalGender
 * 
 * @method integer             getArtistId()          Returns the current record's "artist_id" value
 * @method integer             getMusicalGenderId()   Returns the current record's "musical_gender_id" value
 * @method Artist              getArtist()            Returns the current record's "Artist" value
 * @method MusicalGender       getMusicalGender()     Returns the current record's "MusicalGender" value
 * @method ArtistMusicalGender setArtistId()          Sets the current record's "artist_id" value
 * @method ArtistMusicalGender setMusicalGenderId()   Sets the current record's "musical_gender_id" value
 * @method ArtistMusicalGender setArtist()            Sets the current record's "Artist" value
 * @method ArtistMusicalGender setMusicalGender()     Sets the current record's "MusicalGender" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtistMusicalGender extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist_musical_gender');
        $this->hasColumn('artist_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('musical_gender_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MusicalGender', array(
             'local' => 'musical_gender_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}