<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Track', 'doctrine');

/**
 * BaseTrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Album
 * @property Artist $Artist
 * @property Doctrine_Collection $MusicalGender
 * @property Product $Product
 * 
 * @method Doctrine_Collection getAlbum()         Returns the current record's "Album" collection
 * @method Artist              getArtist()        Returns the current record's "Artist" value
 * @method Doctrine_Collection getMusicalGender() Returns the current record's "MusicalGender" collection
 * @method Product             getProduct()       Returns the current record's "Product" value
 * @method Track               setAlbum()         Sets the current record's "Album" collection
 * @method Track               setArtist()        Sets the current record's "Artist" value
 * @method Track               setMusicalGender() Sets the current record's "MusicalGender" collection
 * @method Track               setProduct()       Sets the current record's "Product" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrack extends tdTrack
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Album', array(
             'refClass' => 'AlbumTrack',
             'local' => 'track_id',
             'foreign' => 'album_id'));

        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));

        $this->hasMany('MusicalGender', array(
             'refClass' => 'TrackMusicalGender',
             'local' => 'track_id',
             'foreign' => 'musical_gender_id'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}