<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Album', 'doctrine');

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $MusicalGender
 * @property Artist $Artist
 * @property Product $Product
 * @property Doctrine_Collection $AlbumsMusicalGenders
 * @property Doctrine_Collection $tracks
 * @property Doctrine_Collection $AlbumsTracks
 * 
 * @method Doctrine_Collection getMusicalGender()        Returns the current record's "MusicalGender" collection
 * @method Artist              getArtist()               Returns the current record's "Artist" value
 * @method Product             getProduct()              Returns the current record's "Product" value
 * @method Doctrine_Collection getAlbumsMusicalGenders() Returns the current record's "AlbumsMusicalGenders" collection
 * @method Doctrine_Collection getTracks()               Returns the current record's "tracks" collection
 * @method Doctrine_Collection getAlbumsTracks()         Returns the current record's "AlbumsTracks" collection
 * @method Album               setMusicalGender()        Sets the current record's "MusicalGender" collection
 * @method Album               setArtist()               Sets the current record's "Artist" value
 * @method Album               setProduct()              Sets the current record's "Product" value
 * @method Album               setAlbumsMusicalGenders() Sets the current record's "AlbumsMusicalGenders" collection
 * @method Album               setTracks()               Sets the current record's "tracks" collection
 * @method Album               setAlbumsTracks()         Sets the current record's "AlbumsTracks" collection
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends tdTrackAlbum
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MusicalGender', array(
             'refClass' => 'AlbumMusicalGender',
             'local' => 'album_id',
             'foreign' => 'musical_gender_id'));

        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasMany('AlbumMusicalGender as AlbumsMusicalGenders', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $this->hasMany('Track as tracks', array(
             'refClass' => 'AlbumTrack',
             'local' => 'album_id',
             'foreign' => 'track_id'));

        $this->hasMany('AlbumTrack as AlbumsTracks', array(
             'local' => 'id',
             'foreign' => 'album_id'));
    }
}