<?php

/**
 * BasetdLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $description
 * @property boolean $active
 * 
 * @method string  getUrl()         Returns the current record's "url" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method boolean getActive()      Returns the current record's "active" value
 * @method tdLink  setUrl()         Sets the current record's "url" value
 * @method tdLink  setDescription() Sets the current record's "description" value
 * @method tdLink  setActive()      Sets the current record's "active" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('td_link');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));


        $this->index('active_index', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}