<?php

/**
 * BasetdSubpage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $content
 * @property boolean $active
 * 
 * @method string    getName()    Returns the current record's "name" value
 * @method string    getContent() Returns the current record's "content" value
 * @method boolean   getActive()  Returns the current record's "active" value
 * @method tdSubpage setName()    Sets the current record's "name" value
 * @method tdSubpage setContent() Sets the current record's "content" value
 * @method tdSubpage setActive()  Sets the current record's "active" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdSubpage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('td_subpage');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}