<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/14 17:29:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bdddeevox',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
