<?php

/**
 * tdTrackAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdTrackAlbumTable extends PlugintdTrackAlbumTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdTrackAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdTrackAlbum');
    }
}