<?php

/**
 * tdTrackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdTrackTable extends PlugintdTrackTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdTrackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdTrack');
    }
}