<?php

/**
 * AlbumMusicalGenderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumMusicalGenderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumMusicalGenderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumMusicalGender');
    }
}