<?php

/**
 * ArtistMusicalGenderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistMusicalGenderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistMusicalGenderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArtistMusicalGender');
    }
}