<?php

/**
 * ArtistMusicalInstrumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistMusicalInstrumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistMusicalInstrumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArtistMusicalInstrument');
    }
}