<?php

/**
 * ArtistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artist');
    }
	
	public function listAllArtists(Doctrine_Query $q = null)
	{
		return $this->getArtistsQuery($q)->execute();
	}
	
	public function retrieveArtist(Doctrine_Query $q = null)
	{
		return $this->getArtistsQuery($q)->fetchOne();
	}
	
	public function countArtist(Doctrine_Query $q = null)
	{
		return $this->getArtistsQuery($q)->count();
	}
	
	
	public function getArtistsQuery(Doctrine_Query $q = null)
	{
		if (is_null($q))
		{
		  $q = Doctrine_Query::create()
			->from('Artist a');
		}
	 
		return $q;
	}
}