<?php

/**
 * DeevoThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeevoThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeevoThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeevoTheme');
    }
}