<?php

/**
 * DeevonauteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeevonauteTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeevonauteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Deevonaute');
    }
}