<?php

/**
 * DeevoThemeUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeevoThemeUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeevoThemeUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeevoThemeUser');
    }
}