<?php

/**
 * MusicalGenderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MusicalGenderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MusicalGenderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MusicalGender');
    }
}