<?php

/**
 * TrackMusicalGenderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrackMusicalGenderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrackMusicalGenderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrackMusicalGender');
    }
}