<?php

/**
 * TrackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrackTable extends tdTrackTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Track');
    }
}