# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            4be56a77fd06ae217873d00afe51dd756b26becf
    # For others modules
    enabled_modules:       [default, sfGuardUser, sfGuardAuth, sfGuardRegister, sfGuardForgotPassword, sfApply, sfFacebookConnectAuth, sfFacebookConnectDemo, cart, tdSampleArticle, comment]
 
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    #internationalisation
    i18n: true
    default_culture:        en
    standard_helpers:       [Partial, Cache, I18N, jQuery]
    jquery_web_dir:         /sfJqueryReloadedPlugin
    jquery_core:            jquery-1.7.min.js
    jquery_sortable:        jquery-ui-1.7.2.custom.min.js
    jquery_autocomplete:    jquery.autocomplete.min.js
