
new:
  is_secure:     false
 
create:
  is_secure:     false
 
delete:
  is_secure:     on
  credentials:  [admin]

show:
  is_secure:     on
  credentials:  [deevonaute]

edit:
  is_secure:     on
  credentials:  [deevonaute]

update:
  is_secure:     on
  credentials:  [deevonaute]

default:
  is_secure:   on
  credentials: [Ecritue]
 
 