<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment', 'comment_reply_comment_id', array(
             'name' => 'comment_reply_comment_id',
             'local' => 'reply',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             ));
        $this->createForeignKey('comment_report', 'comment_report_id_comment_comment_id', array(
             'name' => 'comment_report_id_comment_comment_id',
             'local' => 'id_comment',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('comment', 'comment_reply', array(
             'fields' => 
             array(
              0 => 'reply',
             ),
             ));
        $this->addIndex('comment_report', 'comment_report_id_comment', array(
             'fields' => 
             array(
              0 => 'id_comment',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment', 'comment_reply_comment_id');
        $this->dropForeignKey('comment_report', 'comment_report_id_comment_comment_id');
        $this->removeIndex('comment', 'comment_reply', array(
             'fields' => 
             array(
              0 => 'reply',
             ),
             ));
        $this->removeIndex('comment_report', 'comment_report_id_comment', array(
             'fields' => 
             array(
              0 => 'id_comment',
             ),
             ));
    }
}