<?php

/**
 * BasetdArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $author_id
 * @property clob $text
 * @property string $image
 * @property boolean $active
 * @property string $type
 * @property sfGuardUser $Author
 * 
 * @method string      getTitle()     Returns the current record's "title" value
 * @method integer     getAuthorId()  Returns the current record's "author_id" value
 * @method clob        getText()      Returns the current record's "text" value
 * @method string      getImage()     Returns the current record's "image" value
 * @method boolean     getActive()    Returns the current record's "active" value
 * @method string      getType()      Returns the current record's "type" value
 * @method sfGuardUser getAuthor()    Returns the current record's "Author" value
 * @method tdArticle   setTitle()     Sets the current record's "title" value
 * @method tdArticle   setAuthorId()  Sets the current record's "author_id" value
 * @method tdArticle   setText()      Sets the current record's "text" value
 * @method tdArticle   setImage()     Sets the current record's "image" value
 * @method tdArticle   setActive()    Sets the current record's "active" value
 * @method tdArticle   setType()      Sets the current record's "type" value
 * @method tdArticle   setAuthor()    Sets the current record's "Author" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('td_article');
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('author_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');

        $this->setSubClasses(array(
             'Article' => 
             array(
              'type' => 'Article',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}