<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/11/16 19:36:41
$this->security = array (
  'settings' => 
  array (
    'is_secure' => true,
  ),
  'editemail' => 
  array (
    'is_secure' => true,
  ),
  'reset' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
