<?php

/**
 * tdConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdConfigTable extends PlugintdConfigTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdConfig');
    }
}