<?php

/**
 * tdLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdLinkTable extends PlugintdLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdLink');
    }
}