<?php

/**
 * tdSubpageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdSubpageTable extends PlugintdSubpageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdSubpageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdSubpage');
    }
}