<?php

/**
 * tdArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdArticleTable extends PlugintdArticleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdArticle');
    }
	
	public function listAllArticles(Doctrine_Query $q = null)
	{
		return $this->getArticlesQuery($q)->execute();
	}
	
	public function retrieveArticle(Doctrine_Query $q = null)
	{
		return $this->getArticlesQuery($q)->fetchOne();
	}
	
	public function countArticle(Doctrine_Query $q = null)
	{
		return $this->getArticlesQuery($q)->count();
	}
	
	
	public function getArticlesQuery(Doctrine_Query $q = null)
	{
		if (is_null($q))
		{
		  $q = Doctrine_Query::create()
			->from('tdArticle td_a');
		}
	 
		return $q;
	}
}