<?php

/**
 * BaseTax
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $region_code
 * @property double $rate
 * 
 * @method string getRegionCode()  Returns the current record's "region_code" value
 * @method double getRate()        Returns the current record's "rate" value
 * @method Tax    setRegionCode()  Sets the current record's "region_code" value
 * @method Tax    setRate()        Sets the current record's "rate" value
 * 
 * @package    deevox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTax extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sfCartTax');
        $this->hasColumn('region_code', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('rate', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}